
HEIGHT = 750
WIDTH = 1200
FPS = 60
FOOD_SPAWN_TIME = 1000 # seconds
APPLE_SPAWN_CHANCE = 75 # should be always greater than golden apple spawn chance
GOLDEN_APPLE_SPAWN_CHANCE = 25
SNAKE_SPEED = 10
SCORE_INCREMENT_GREEN = 10
SCORE_INCREMENT_GOLDEN = SCORE_INCREMENT_GREEN * 2
FONT = 'Arial'
FONT_SIZE = 32
GROW_SIZE_GOLDEN_APPLE = 3
GROW_SIZE_APPLE = 1
HIGH_SCORE = 0